version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    depends_on:
      - db

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: